services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
      - "5433:5432"
    volumes:
      # This named volume persists the PostgreSQL data across container restarts
      - postgres_data:/var/lib/postgresql/data
      - ./.env:/app/.env:ro
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/gcp-credentials.json:ro
    environment:
      - POWERCORD_DB_HOST=localhost:5432
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
      - GOOGLE_CLOUD_PROJECT=${POWERCORD_GCP_PROJECT}
    env_file:
      - .env

volumes:
  postgres_data:
