"""add_security_alert_overrides

Revision ID: 0caed23d30a5
Revises: f9e3c8d1e7b6
Create Date: 2026-06-21 19:32:30.394107

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0caed23d30a5"
down_revision: Union[str, Sequence[str], None] = "f9e3c8d1e7b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_alert_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("alert_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rule", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_alert_overrides_alert_hash"), "security_alert_overrides", ["alert_hash"], unique=False
    )
    op.create_index(
        op.f("ix_security_alert_overrides_guild_id"), "security_alert_overrides", ["guild_id"], unique=False
    )
    op.alter_column(
        "widget_settings", "position_config", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "widget_settings", "position_config", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True
    )
    op.drop_index(op.f("ix_security_alert_overrides_guild_id"), table_name="security_alert_overrides")
    op.drop_index(op.f("ix_security_alert_overrides_alert_hash"), table_name="security_alert_overrides")
    op.drop_table("security_alert_overrides")
    # ### end Alembic commands ###
