"""add midi library tables and drop orphaned hero table

Revision ID: 0d691a5a07c0
Revises: 6991c1eb9a2f
Create Date: 2026-03-04 10:53:50.650370

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d691a5a07c0"
down_revision: Union[str, Sequence[str], None] = "6991c1eb9a2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — conditionally drops the orphaned hero table if it exists."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "hero" in inspector.get_table_names():
        op.drop_table("hero")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("secret_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("hero_pkey")),
    )
    # ### end Alembic commands ###
