""" "add_api_keys_and_access_roles"

Revision ID: 1c7fc4ef8015
Revises: ef5054faa23a
Create Date: 2026-03-08 10:16:44.762594

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c7fc4ef8015"
down_revision: Union[str, Sequence[str], None] = "ef5054faa23a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed accidental drops of extension tables due to autogenerate while uninstalled:
    # op.drop_table("midimeta")
    # op.drop_index(op.f("ix_honeypot_ban_reports_guild_id"), table_name="honeypot_ban_reports")
    # op.drop_index(op.f("ix_honeypot_ban_reports_user_id"), table_name="honeypot_ban_reports")
    # op.drop_table("honeypot_ban_reports")
    # op.drop_index(op.f("ix_honeypot_channels_guild_id"), table_name="honeypot_channels")
    # op.drop_table("honeypot_channels")
    # op.drop_index(op.f("ix_midiinstrument_checksum"), table_name="midiinstrument")
    # op.drop_table("midiinstrument")
    # op.drop_table("midifile")
    # op.drop_index(op.f("ix_honeypot_settings_guild_id"), table_name="honeypot_settings")
    # op.drop_table("honeypot_settings")
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "hero" in inspector.get_table_names():
        op.drop_table("hero")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("secret_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("hero_pkey")),
    )
    # Removed accidental recreations in downgrade
    # op.create_table(
    #     "honeypot_settings",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=True),
    #     sa.Column("time_limit", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("log_channel_id", sa.BIGINT(), autoincrement=False, nullable=True),
    #     sa.Column("shame_mode", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("id", name=op.f("honeypot_settings_pkey")),
    # )
    # op.create_index(op.f("ix_honeypot_settings_guild_id"), "honeypot_settings", ["guild_id"], unique=True)
    # op.create_table(
    #     "midifile",
    #     sa.Column("checksum", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("contributor", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("tags", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.PrimaryKeyConstraint("checksum", name=op.f("midifile_pkey")),
    # )
    # op.create_table(
    #     "midiinstrument",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("checksum", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("instrument", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("instrument_class", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("is_drum", sa.BOOLEAN(), autoincrement=False, nullable=False),
    #     sa.Column("note_count", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(["checksum"], ["midifile.checksum"], name=op.f("midiinstrument_checksum_fkey")),
    #     sa.PrimaryKeyConstraint("id", name=op.f("midiinstrument_pkey")),
    # )
    # op.create_index(op.f("ix_midiinstrument_checksum"), "midiinstrument", ["checksum"], unique=False)
    # op.create_table(
    #     "honeypot_channels",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=True),
    #     sa.Column("channel_id", sa.BIGINT(), autoincrement=False, nullable=True),
    #     sa.Column("added_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("id", name=op.f("honeypot_channels_pkey")),
    #     sa.UniqueConstraint(
    #         "channel_id",
    #         name=op.f("honeypot_channels_channel_id_key"),
    #         postgresql_include=[],
    #         postgresql_nulls_not_distinct=False,
    #     ),
    # )
    # op.create_index(op.f("ix_honeypot_channels_guild_id"), "honeypot_channels", ["guild_id"], unique=False)
    # op.create_table(
    #     "honeypot_ban_reports",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=True),
    #     sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=True),
    #     sa.Column("username", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    #     sa.Column("banned_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    #     sa.Column("reason", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("id", name=op.f("honeypot_ban_reports_pkey")),
    # )
    # op.create_index(op.f("ix_honeypot_ban_reports_user_id"), "honeypot_ban_reports", ["user_id"], unique=False)
    # op.create_index(op.f("ix_honeypot_ban_reports_guild_id"), "honeypot_ban_reports", ["guild_id"], unique=False)
    # op.create_table(
    #     "midimeta",
    #     sa.Column("checksum", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column("num_instruments", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("total_notes", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("drum_percent", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("dup_percent", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("dup_count", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("track_diversity", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    #     sa.Column("quality_score", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(["checksum"], ["midifile.checksum"], name=op.f("midimeta_checksum_fkey")),
    #     sa.PrimaryKeyConstraint("checksum", name=op.f("midimeta_pkey")),
    # )
    # ### end Alembic commands ###
