"""initial_core

Revision ID: 4d30ec975899
Revises: 
Create Date: 2026-04-10 21:58:45.309630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d30ec975899'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    if 'admin_users' not in existing_tables:
        op.create_table('admin_users',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint('user_id')
        )
    if 'api_access_roles' not in existing_tables:
        op.create_table('api_access_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=True),
        sa.Column('role_id', sa.BigInteger(), nullable=True),
        sa.Column('extension_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_api_access_roles_guild_id'), 'api_access_roles', ['guild_id'], unique=False)
    if 'api_keys' not in existing_tables:
        op.create_table('api_keys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    if 'custom_content_items' not in existing_tables:
        op.create_table('custom_content_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('has_frame', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_custom_content_items_guild_id'), 'custom_content_items', ['guild_id'], unique=False)
    if 'dashboard_access_roles' not in existing_tables:
        op.create_table('dashboard_access_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=True),
        sa.Column('role_id', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_dashboard_access_roles_guild_id'), 'dashboard_access_roles', ['guild_id'], unique=False)
    if 'discord_channels' not in existing_tables:
        op.create_table('discord_channels',
        sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=True),
        sa.Column('parent_id', sa.BigInteger(), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('overwrites', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_discord_channels_guild_id'), 'discord_channels', ['guild_id'], unique=False)
    if 'discord_roles' not in existing_tables:
        op.create_table('discord_roles',
        sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('permissions', sa.BigInteger(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('color', sa.Integer(), nullable=False),
        sa.Column('is_hoisted', sa.Boolean(), nullable=False),
        sa.Column('is_managed', sa.Boolean(), nullable=False),
        sa.Column('is_mentionable', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_discord_roles_guild_id'), 'discord_roles', ['guild_id'], unique=False)
    if 'guild_extension_settings' not in existing_tables:
        op.create_table('guild_extension_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=True),
        sa.Column('extension_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('gadget_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if 'todoitem' not in existing_tables:
        op.create_table('todoitem',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_completed', sa.Boolean(), nullable=False),
        sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if 'widget_settings' not in existing_tables:
        op.create_table('widget_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=True),
        sa.Column('extension_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('widget_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('column_span', sa.Integer(), nullable=False),
        sa.Column('grid_x', sa.Integer(), nullable=False),
        sa.Column('grid_y', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    if 'widget_settings' in existing_tables:
        op.drop_table('widget_settings')
    if 'todoitem' in existing_tables:
        op.drop_table('todoitem')
    if 'guild_extension_settings' in existing_tables:
        op.drop_table('guild_extension_settings')
        op.drop_index(op.f('ix_discord_roles_guild_id'), table_name='discord_roles')
    if 'discord_roles' in existing_tables:
        op.drop_table('discord_roles')
        op.drop_index(op.f('ix_discord_channels_guild_id'), table_name='discord_channels')
    if 'discord_channels' in existing_tables:
        op.drop_table('discord_channels')
        op.drop_index(op.f('ix_dashboard_access_roles_guild_id'), table_name='dashboard_access_roles')
    if 'dashboard_access_roles' in existing_tables:
        op.drop_table('dashboard_access_roles')
        op.drop_index(op.f('ix_custom_content_items_guild_id'), table_name='custom_content_items')
    if 'custom_content_items' in existing_tables:
        op.drop_table('custom_content_items')
        op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    if 'api_keys' in existing_tables:
        op.drop_table('api_keys')
        op.drop_index(op.f('ix_api_access_roles_guild_id'), table_name='api_access_roles')
    if 'api_access_roles' in existing_tables:
        op.drop_table('api_access_roles')
    if 'admin_users' in existing_tables:
        op.drop_table('admin_users')
    # ### end Alembic commands ###
