"""initial_migration

Revision ID: 4df1cf89e983
Revises:
Create Date: 2026-02-12 07:42:32.575602

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4df1cf89e983"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Core framework tables — always created
    op.create_table(
        "guild_extension_settings",
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column(
            "extension_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("gadget_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("guild_id", "extension_name", "gadget_type"),
    )
    op.create_table(
        "widget_settings",
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column(
            "extension_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("widget_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("column_span", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("guild_id", "extension_name", "widget_name"),
    )

    # Honeypot extension tables — only created if the extension is installed.
    # When honeypot is installed later via ext-install, its blueprint will be
    # picked up by alembic autogenerate and a new migration will create them.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    if "honeypot_settings" not in existing_tables:
        from pathlib import Path

        ext_dir = Path(__file__).resolve().parents[2] / "app" / "extensions" / "honeypot"
        if ext_dir.is_dir():
            op.create_table(
                "honeypot_settings",
                sa.Column("guild_id", sa.BigInteger(), nullable=False),
                sa.Column("time_limit", sa.Integer(), nullable=False),
                sa.PrimaryKeyConstraint("guild_id"),
            )
            op.create_index(op.f("ix_honeypot_settings_guild_id"), "honeypot_settings", ["guild_id"], unique=True)
            op.create_table(
                "honeypot_channels",
                sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
                sa.Column("guild_id", sa.BigInteger(), nullable=False),
                sa.Column("channel_id", sa.BigInteger(), nullable=False),
                sa.Column("added_at", sa.DateTime(), nullable=False),
                sa.PrimaryKeyConstraint("id"),
                sa.UniqueConstraint("channel_id"),
            )
            op.create_index(op.f("ix_honeypot_channels_guild_id"), "honeypot_channels", ["guild_id"], unique=False)
            op.create_table(
                "honeypot_ban_reports",
                sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
                sa.Column("guild_id", sa.BigInteger(), nullable=False),
                sa.Column("user_id", sa.BigInteger(), nullable=False),
                sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                sa.Column("banned_at", sa.DateTime(), nullable=False),
                sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
                sa.PrimaryKeyConstraint("id"),
            )
            op.create_index(
                op.f("ix_honeypot_ban_reports_guild_id"), "honeypot_ban_reports", ["guild_id"], unique=False
            )
            op.create_index(op.f("ix_honeypot_ban_reports_user_id"), "honeypot_ban_reports", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("widget_settings")
    op.drop_table("guild_extension_settings")

    # Honeypot tables — only drop if they exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    for table_name in ["honeypot_settings", "honeypot_channels", "honeypot_ban_reports"]:
        if table_name in existing_tables:
            # Drop indexes first
            for idx in inspector.get_indexes(table_name):
                op.drop_index(idx["name"], table_name=table_name)
            op.drop_table(table_name)
    # ### end Alembic commands ###
