""" "message=fix_schema"

Revision ID: 84806fb16462
Revises: 4df1cf89e983
Create Date: 2026-02-15 21:39:20.607783

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84806fb16462"
down_revision: Union[str, Sequence[str], None] = "4df1cf89e983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS todoitem CASCADE")
    op.execute("DROP TABLE IF EXISTS hero CASCADE")
    # 1. Add id column as nullable first
    op.add_column("guild_extension_settings", sa.Column("id", sa.Integer(), nullable=True))
    op.add_column("widget_settings", sa.Column("id", sa.Integer(), nullable=True))

    # 2. Populate the id columns with unique values (using a sequence or row_number approach is complex in generic almanbic,
    # but for sqlite/postgres we can often just let the DB handle it if it was a serial.
    # Since we are adding a primary key, we need unique values.
    # PROPER FIX: Create a sequence and assign it, or just use a loop if data volume is small.
    # SIMPLER FIX for dev env: Delete all data (if acceptable) OR distinct assignment.
    # Let's try to update with a sequence simulation or just raw SQL for postgres.
    # Using hashtext on ctid is a safer way to get an int if point casting fails
    op.execute("UPDATE guild_extension_settings SET id = abs(hashtext(ctid::text))")
    op.execute("UPDATE widget_settings SET id = abs(hashtext(ctid::text))")

    # 3. Alter column to be not null and add primary key
    op.alter_column("guild_extension_settings", "id", nullable=False)
    op.alter_column("widget_settings", "id", nullable=False)

    # 4. Handle constraint changes
    # Drop existing primary key if it exists (assuming guild_id was the PK or part of it)
    # If there was no explicit PK, these drops might fail or be unnecessary.
    # For this specific migration, assuming no prior PK on these tables or that it's being replaced.
    # If guild_id was the PK, we need to drop it before changing its type.
    # The original upgrade had `nullable=True` for the new `guild_id` type.
    # The provided snippet for `guild_id` alter_column does not specify the new `nullable` state.
    # I will retain the original `nullable=True` for the new `BigInteger` type.
    op.drop_constraint("guild_extension_settings_pkey", "guild_extension_settings", type_="primary")
    op.create_primary_key("guild_extension_settings_pkey", "guild_extension_settings", ["id"])

    op.drop_constraint("widget_settings_pkey", "widget_settings", type_="primary")
    op.create_primary_key("widget_settings_pkey", "widget_settings", ["id"])

    # 5. Type changes (BigInteger)
    op.alter_column(
        "guild_extension_settings",
        "guild_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,  # Based on downgrade, guild_id was not nullable before this upgrade
        nullable=True,
    )  # Retaining original upgrade's nullable state for BigInteger
    op.alter_column(
        "widget_settings",
        "guild_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,  # Based on downgrade, guild_id was not nullable before this upgrade
        nullable=True,
    )  # Retaining original upgrade's nullable state for BigInteger
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("widget_settings", "guild_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), nullable=False)
    op.drop_column("widget_settings", "id")
    op.alter_column(
        "guild_extension_settings", "guild_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), nullable=False
    )
    op.drop_column("guild_extension_settings", "id")
    op.create_table(
        "hero",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("secret_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("hero_pkey")),
    )
    op.create_table(
        "todoitem",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("todoitem_pkey")),
    )
    # ### end Alembic commands ###
