"""add_has_frame_to_custom_content

Revision ID: de37210f06b0
Revises: a834c5693087
Create Date: 2026-03-10 22:44:01.628177

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de37210f06b0"
down_revision: Union[str, Sequence[str], None] = "a834c5693087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_content_items", sa.Column("has_frame", sa.Boolean(), nullable=False, server_default=sa.text("true"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_content_items", "has_frame")
    # ### end Alembic commands ###
