"""create_missing_core_tables

Revision ID: f123456789ab
Revises: de37210f06b0
Create Date: 2026-04-10 19:10:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f123456789ab"
down_revision: Union[str, Sequence[str], None] = "de37210f06b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if we're dealing with a database that already has these tables 
    # (e.g. from an old install where create_all() bypassed alembic)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if "admin_users" not in existing_tables:
        op.create_table(
            "admin_users",
            sa.Column("user_id", sa.BigInteger(), nullable=False),
            sa.Column("comment", sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint("user_id"),
        )

    if "discord_roles" not in existing_tables:
        op.create_table(
            "discord_roles",
            sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
            sa.Column("guild_id", sa.BigInteger(), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("permissions", sa.BigInteger(), nullable=False),
            sa.Column("position", sa.Integer(), nullable=False),
            sa.Column("color", sa.Integer(), nullable=False),
            sa.Column("is_hoisted", sa.Boolean(), nullable=False),
            sa.Column("is_managed", sa.Boolean(), nullable=False),
            sa.Column("is_mentionable", sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_discord_roles_guild_id"), "discord_roles", ["guild_id"], unique=False)

    if "discord_channels" not in existing_tables:
        op.create_table(
            "discord_channels",
            sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
            sa.Column("guild_id", sa.BigInteger(), nullable=False),
            sa.Column("parent_id", sa.BigInteger(), nullable=True),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("type", sa.String(length=50), nullable=False),
            sa.Column("position", sa.Integer(), nullable=False),
            sa.Column("overwrites", sa.String(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_discord_channels_guild_id"), "discord_channels", ["guild_id"], unique=False)

    if "dashboard_access_roles" not in existing_tables:
        op.create_table(
            "dashboard_access_roles",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("guild_id", sa.BigInteger(), nullable=False),
            sa.Column("role_id", sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_dashboard_access_roles_guild_id"), "dashboard_access_roles", ["guild_id"], unique=False)

    if "api_keys" not in existing_tables:
        op.create_table(
            "api_keys",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("key", sa.String(length=255), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("scopes", sa.String(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("key"),
            sa.UniqueConstraint("name"),
        )
        op.create_index(op.f("ix_api_keys_key"), "api_keys", ["key"], unique=True)

    if "api_access_roles" not in existing_tables:
        op.create_table(
            "api_access_roles",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("guild_id", sa.BigInteger(), nullable=False),
            sa.Column("role_id", sa.BigInteger(), nullable=False),
            sa.Column("extension_name", sa.String(length=255), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_api_access_roles_guild_id"), "api_access_roles", ["guild_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_access_roles_guild_id"), table_name="api_access_roles")
    op.drop_table("api_access_roles")
    op.drop_index(op.f("ix_api_keys_key"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_dashboard_access_roles_guild_id"), table_name="dashboard_access_roles")
    op.drop_table("dashboard_access_roles")
    op.drop_index(op.f("ix_discord_channels_guild_id"), table_name="discord_channels")
    op.drop_table("discord_channels")
    op.drop_index(op.f("ix_discord_roles_guild_id"), table_name="discord_roles")
    op.drop_table("discord_roles")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
