""" "message=manual_fix_id_sequence"

Revision ID: f93f62c123e1
Revises: 538f3c91e146
Create Date: 2026-02-15 21:49:05.979566

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f93f62c123e1"
down_revision: Union[str, Sequence[str], None] = "538f3c91e146"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual sequence creation for guild_extension_settings
    op.execute("CREATE SEQUENCE guild_extension_settings_id_seq")
    op.execute(
        "ALTER TABLE guild_extension_settings ALTER COLUMN id SET DEFAULT nextval('guild_extension_settings_id_seq')"
    )
    op.execute("ALTER SEQUENCE guild_extension_settings_id_seq OWNED BY guild_extension_settings.id")
    op.execute(
        "SELECT setval('guild_extension_settings_id_seq', COALESCE((SELECT MAX(id) FROM guild_extension_settings), 1))"
    )

    # Manual sequence creation for widget_settings
    op.execute("CREATE SEQUENCE widget_settings_id_seq")
    op.execute("ALTER TABLE widget_settings ALTER COLUMN id SET DEFAULT nextval('widget_settings_id_seq')")
    op.execute("ALTER SEQUENCE widget_settings_id_seq OWNED BY widget_settings.id")
    op.execute("SELECT setval('widget_settings_id_seq', COALESCE((SELECT MAX(id) FROM widget_settings), 1))")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todoitem",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("todoitem_pkey")),
    )
    # ### end Alembic commands ###
